	-- MySQL Script generated by MySQL Workbench
	-- Thu Apr 27 23:31:42 2023
	-- Model: New Model    Version: 1.0
	-- MySQL Workbench Forward Engineering

	SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
	SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
	SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

	-- -----------------------------------------------------
	-- Schema mydb
	-- -----------------------------------------------------
	DROP SCHEMA IF EXISTS `mydb` ;

	-- -----------------------------------------------------
	-- Schema mydb
	-- -----------------------------------------------------
	CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
	USE `mydb` ;

	-- -----------------------------------------------------
	-- Table `mydb`.`CuentaBanco`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`CuentaBanco` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`CuentaBanco` (
	  `id_cuenta_banco` INT NOT NULL,
	  `numero_cuenta` VARCHAR(45) NOT NULL,
	  `saldo` INT NOT NULL,
	  `estado_cuenta` INT NOT NULL,
	  `fecha_apertura` DATE NOT NULL,
	  `fecha_cierre` DATE NULL DEFAULT NULL,
	  `tipo_moneda` VARCHAR(45) NOT NULL,
	  `iban` VARCHAR(45) NOT NULL,
	  `pais` VARCHAR(45) NOT NULL,
	  `sospechoso` TINYINT NOT NULL,
	  PRIMARY KEY (`id_cuenta_banco`),
	  UNIQUE INDEX `id_cuenta_banco_UNIQUE` (`id_cuenta_banco` ASC) VISIBLE)
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`Direccion`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`Direccion` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
	  `id_direccion` INT NOT NULL AUTO_INCREMENT,
	  `calle` VARCHAR(100) NOT NULL,
	  `numero` VARCHAR(45) NOT NULL,
	  `puerta` VARCHAR(45) NOT NULL,
	  `ciudad` VARCHAR(45) NOT NULL,
	  `pais` VARCHAR(45) NOT NULL,
	  `cp` VARCHAR(45) NOT NULL,
	  `region` VARCHAR(45) NULL DEFAULT NULL,
	  `valida` TINYINT NOT NULL,
	  PRIMARY KEY (`id_direccion`))
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`Empresa`
	DROP TABLE IF EXISTS `mydb`.`Empresa` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
	  `id_empresa` INT NOT NULL AUTO_INCREMENT,
	  `cif` VARCHAR(45) NOT NULL,
	  `nombre` VARCHAR(100) NOT NULL,
	  `Direccion_id_direccion` INT NOT NULL,
	  `cuenta_empresa_id_cuenta_banco` INT,
      `estado_empresa` VARCHAR(45) NOT NULL DEFAULT 'activa',
	  PRIMARY KEY (`id_empresa`),
	  UNIQUE INDEX `id_empresa_UNIQUE` (`id_empresa` ASC) VISIBLE,
	  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
	  UNIQUE INDEX `cif_UNIQUE` (`cif` ASC) VISIBLE,
	  INDEX `fk_Empresa_CuentaBanco_idx` (`cuenta_empresa_id_cuenta_banco` ASC) VISIBLE,
	  INDEX `fk_Empresa_Direccion1_idx` (`Direccion_id_direccion` ASC) VISIBLE,

	  CONSTRAINT `fk_Empresa_CuentaBanco`
	    FOREIGN KEY (`cuenta_empresa_id_cuenta_banco`)
	    REFERENCES `mydb`.`CuentaBanco` (`id_cuenta_banco`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	  CONSTRAINT `fk_Empresa_Direccion1`
	    FOREIGN KEY (`Direccion_id_direccion`)
	    REFERENCES `mydb`.`Direccion` (`id_direccion`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION)
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`Usuario`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`Usuario` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
	  `id_usuario` INT NOT NULL AUTO_INCREMENT,
	  `nif` VARCHAR(45) NOT NULL,
	  `nombre` VARCHAR(45) NOT NULL,
	  `segundo_nombre` VARCHAR(45) NULL DEFAULT NULL,
	  `primer_apellido` VARCHAR(45) NOT NULL,
	  `segundo_apellido` VARCHAR(45) NULL DEFAULT NULL,
	  `fecha_nacimiento` DATE NOT NULL,
	  `contrasena` VARCHAR(45) NOT NULL,
	  `fecha_inicio` DATE NOT NULL,
	  `cuenta_banco_id_cuenta_banco` INT,
	  `Empresa_id_empresa` INT,
	  `Direccion_id_direccion` INT NOT NULL,
	  `tipo_usuario` VARCHAR(45) NOT NULL,
	  `estado_usuario` VARCHAR(45) NOT NULL,
	  `tipo_persona_relacionada` VARCHAR(45) NULL,
	  PRIMARY KEY (`id_usuario`),
	  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
	  INDEX `fk_Usuario_CuentaBanco_idx` (`cuenta_banco_id_cuenta_banco` ASC) VISIBLE,
	  INDEX `fk_Usuario_Empresa1_idx` (`Empresa_id_empresa` ASC) VISIBLE,
	  INDEX `fk_Usuario_Direccion1_idx` (`Direccion_id_direccion` ASC) VISIBLE,
	  CONSTRAINT `fk_Usuario_CuentaBanco`
	    FOREIGN KEY (`cuenta_banco_id_cuenta_banco`)
	    REFERENCES `mydb`.`CuentaBanco` (`id_cuenta_banco`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	  CONSTRAINT `fk_Usuario_Empresa1`
	    FOREIGN KEY (`Empresa_id_empresa`)
	    REFERENCES `mydb`.`Empresa` (`id_empresa`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	  CONSTRAINT `fk_Usuario_Direccion1`
	    FOREIGN KEY (`Direccion_id_direccion`)
	    REFERENCES `mydb`.`Direccion` (`id_direccion`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION)
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`CambioDivisa`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`CambioDivisa` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`CambioDivisa` (
	  `id_cambio_divisa` INT NOT NULL,
	  `moneda_venta` VARCHAR(45) NOT NULL,
	  `moneda_compra` VARCHAR(45) NOT NULL,
	  `cantidad_compra` INT NOT NULL,
	  `cantidad_venta` INT NOT NULL,
	  PRIMARY KEY (`id_cambio_divisa`))
	ENGINE = InnoDB;



	-- -----------------------------------------------------
	-- Table `mydb`.`Pago`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`Pago` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
	  `id_pago` INT NOT NULL AUTO_INCREMENT,
	  `moneda` VARCHAR(45) NOT NULL,
	  `cantidad` INT NOT NULL,
	  `iban_beneficiario` VARCHAR(45),
	  PRIMARY KEY (`id_pago`))
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`Transaccion`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`Transaccion` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`Transaccion` (
	  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
	  `fecha_instruccion` DATE NOT NULL,
	  `fecha_ejecucion` DATE NULL DEFAULT NULL,
	  `cuenta_banco_id_cuenta_banco` INT NOT NULL,
	  `cambio_divisa_id_cambio_divisa` INT,
	  `Pago_id_pago` INT,
	  `id_usuario_actor` INT,
	  PRIMARY KEY (`id_transaccion`),
	  INDEX `fk_Transaccion_CuentaBanco1_idx` (`cuenta_banco_id_cuenta_banco` ASC) VISIBLE,
	  INDEX `fk_Transaccion_CambioDivisa1_idx` (`cambio_divisa_id_cambio_divisa` ASC) VISIBLE,
	  INDEX `fk_Transaccion_Pago1_idx` (`Pago_id_pago` ASC) VISIBLE,
	  CONSTRAINT `fk_Transaccion_CuentaBanco1`
	    FOREIGN KEY (`cuenta_banco_id_cuenta_banco`)
	    REFERENCES `mydb`.`CuentaBanco` (`id_cuenta_banco`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	  CONSTRAINT `fk_Transaccion_CambioDivisa1`
	    FOREIGN KEY (`cambio_divisa_id_cambio_divisa`)
	    REFERENCES `mydb`.`CambioDivisa` (`id_cambio_divisa`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	  CONSTRAINT `fk_Transaccion_Pago1`
	    FOREIGN KEY (`Pago_id_pago`)
	    REFERENCES `mydb`.`Pago` (`id_pago`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION)
	ENGINE = InnoDB;


	-- -----------------------------------------------------
	-- Table `mydb`.`Peticion`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`Peticion` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`Peticion` (
	  `id_peticion` INT NOT NULL AUTO_INCREMENT,
	  `tipo_peticion` VARCHAR(45) NOT NULL,
	  `fecha_peticion` DATETIME NULL,
	  `Usuario_id_usuario` INT,
	  `estado_peticion` VARCHAR(45) NOT NULL,
      `Empresa_id_empresa` INT,
	  PRIMARY KEY (`id_peticion`),
	  INDEX `fk_Peticion_Usuario1_idx` (`Usuario_id_usuario` ASC) VISIBLE,
      INDEX `fk_Peticion_Empresa1_idx` (`Empresa_id_empresa` ASC) VISIBLE,
	  CONSTRAINT `fk_Peticion_Usuario1`
	    FOREIGN KEY (`Usuario_id_usuario`)
	    REFERENCES `mydb`.`Usuario` (`id_usuario`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
        CONSTRAINT `fk_Peticion_Empresa1`
	    FOREIGN KEY (`Empresa_id_empresa`)
	    REFERENCES `mydb`.`Empresa` (`id_empresa`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION)
	ENGINE = InnoDB;

	-- -----------------------------------------------------
	-- Table `mydb`.`mensaje`
	-- -----------------------------------------------------
	DROP TABLE IF EXISTS `mydb`.`mensaje` ;

	CREATE TABLE IF NOT EXISTS `mydb`.`mensaje` (
	  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
	  `contenido` VARCHAR(256) NOT NULL,
	  `fecha_envio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	  `usuario_destino` INT NOT NULL,
	  `usuario_origen` INT NOT NULL,
	  PRIMARY KEY (`id_mensaje`),
	  UNIQUE INDEX `id_mensaje_UNIQUE` (`id_mensaje` ASC) VISIBLE,
	  INDEX `usuario_destino_idx` (`usuario_destino` ASC) VISIBLE,
	  INDEX `usuario_origen_idx` (`usuario_origen` ASC) VISIBLE,
	  CONSTRAINT `usuario_destino`
	    FOREIGN KEY (`usuario_destino`)
	    REFERENCES `mydb`.`usuario` (`id_usuario`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	  CONSTRAINT `usuario_origen`
	    FOREIGN KEY (`usuario_origen`)
	    REFERENCES `mydb`.`usuario` (`id_usuario`)
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION)
	ENGINE = InnoDB
	DEFAULT CHARACTER SET = utf8mb3;


	SET SQL_MODE=@OLD_SQL_MODE;
	SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
	SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
